/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8c582fef-1d36-4dd1-b0fa-20ab7c3ca1eb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8rzdOpiz5",
    "aws_user_pools_web_client_id": "59d9d44gbj46100ej88sdqipop",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "clientmobile-storage-22ef2adf170406-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
